version: '3.3'
services:
  perime-busqueda-ms:
    image: golang:latest
    volumes:
      - .:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    command: go run main.go
    ports:
      - "4000:4000"
  perime-busqueda-db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'busqueda-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - busqueda-db:/var/lib/mariadb
# Names our volume
volumes:
  busqueda-db:
